/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 05 18:56:23 GMT 2017
 */

package helloWorld;

import org.junit.Test;
import static org.junit.Assert.*;
import helloWorld.HelloWorld;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelloWorld_ESTest extends HelloWorld_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HelloWorld helloWorld0 = new HelloWorld();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[8];
      HelloWorld.main(stringArray0);
  }
}
